### ISSUE TITLE
AVD_Minimal.zip

### ISSUE THREAD

**Issue by ding15963** [wqynew/NeoNav#1]
This is the given link for the AVD minimal dataset https://storage.googleapis.com/active-vision-dataset/AVD_Minimal.zip However this link foes not work. Could you please provide the correct working link for the same? Thanks!

**Comment by wqynew** [comment]
I have changed the link. Thanks.

**Comment by ding15963** [comment]
@wqynew Thank you! I may need the complete AVD Minimal dataset, the official link https://storage.googleapis.com/active-vision-dataset/AVD_Minimal.zip is invalid, do you have a backup file to share, thank you very much!

**Comment by wqynew** [comment]
I am sorry. We just keep the rgb_imgs.npy and the depth_imgs.npy files. Thanks.
